fn main() {
    tauri_build::build();
    generate_payload_module();
}

/// Generate a Rust module that embeds all payload files into the binary.
///
/// The CLI copies target app files into `payload/` and writes a
/// `payload-manifest.json` before invoking `cargo tauri build`.
/// This build script reads those and produces `payload_data.rs` in OUT_DIR.
fn generate_payload_module() {
    let out_dir = std::env::var("OUT_DIR").unwrap();
    let dest_path = std::path::Path::new(&out_dir).join("payload_data.rs");

    let manifest_path = std::path::Path::new("payload-manifest.json");
    let payload_dir = std::path::Path::new("payload");

    // Resolve absolute path for the payload directory.
    // include_bytes! paths are resolved relative to the file containing them
    // (which is in OUT_DIR), so we need absolute paths.
    let payload_dir_abs = std::env::current_dir()
        .unwrap()
        .join("payload");

    // No payload → generate empty stubs (dev / preview mode).
    if !manifest_path.exists() || !payload_dir.exists() {
        let code = r#"
// Auto-generated by build.rs — no payload present (dev / preview mode).
pub const MANIFEST_JSON: &str = "{}";
pub static FILES: &[(&str, &[u8])] = &[];
"#;
        std::fs::write(&dest_path, code).unwrap();
        println!("cargo:warning=No payload found — building in preview mode.");
        return;
    }

    println!("cargo:rerun-if-changed=payload-manifest.json");
    println!("cargo:rerun-if-changed=payload");

    let manifest_json =
        std::fs::read_to_string(manifest_path).expect("Failed to read payload-manifest.json");

    let mut code = String::new();

    // Embed manifest as an escaped string (Rust 2024 reserves multi-hash raw strings).
    let escaped_manifest = manifest_json
        .replace('\\', "\\\\")
        .replace('"', "\\\"")
        .replace('\n', "\\n")
        .replace('\r', "\\r");
    code.push_str(&format!(
        "pub const MANIFEST_JSON: &str = \"{}\";\n\n",
        escaped_manifest
    ));

    // Embed each payload file.
    code.push_str("pub static FILES: &[(&str, &[u8])] = &[\n");

    let manifest: serde_json::Value =
        serde_json::from_str(&manifest_json).expect("Invalid payload-manifest.json");

    if let Some(files) = manifest.get("payload_files").and_then(|v| v.as_array()) {
        for file_entry in files {
            let relative = file_entry.as_str().unwrap();
            let file_path = payload_dir.join(relative);
            let escaped = relative.replace('\\', "\\\\").replace('"', "\\\"");

            println!("cargo:rerun-if-changed={}", file_path.display());

            if file_path.exists() {
                // Use absolute path so include_bytes! works from OUT_DIR.
                let abs_path = payload_dir_abs.join(relative);
                code.push_str(&format!(
                    "    (\"{}\", include_bytes!(\"{}\")),\n",
                    escaped,
                    abs_path.display().to_string().replace('\\', "\\\\")
                ));
            } else {
                println!(
                    "cargo:warning=Payload file not found: {}",
                    file_path.display()
                );
            }
        }
    }

    code.push_str("];\n");

    std::fs::write(&dest_path, &code).unwrap();
    println!(
        "cargo:warning=Embedded {} payload file(s).",
        manifest
            .get("payload_files")
            .and_then(|v| v.as_array())
            .map(|a| a.len())
            .unwrap_or(0)
    );
}
