//! `parcel clean` — rollback local build artifacts for development.
//!
//! This command cleans up the output of `parcel build` in the current
//! project directory, allowing developers to start fresh or undo a build
//! that went wrong.
//!
//! By default it removes only the build cache (`.parcel-build/`).
//! With `--dist` it also removes the `dist/` output directory.
//! With `--all` it additionally removes `parcel.json` and `parcel/`.

use anyhow::{Context, Result};
use std::path::Path;

/// What to clean.
#[derive(Debug, Clone, Copy)]
pub struct CleanOptions {
    /// Also remove `dist/` output directory.
    pub include_dist: bool,
    /// Also remove `parcel.json` and `parcel/` (full reset).
    pub include_config: bool,
    /// Dry-run: show what would be removed without actually removing.
    pub dry_run: bool,
}

/// Run the `parcel clean` command.
#[allow(dead_code)]
pub fn run() -> Result<()> {
    // Default: clean build artifacts only.
    let opts = CleanOptions {
        include_dist: false,
        include_config: false,
        dry_run: false,
    };
    clean(opts)
}

/// Run with options (called from CLI argument parsing).
pub fn run_with_options(include_dist: bool, include_config: bool, dry_run: bool) -> Result<()> {
    clean(CleanOptions {
        include_dist,
        include_config,
        dry_run,
    })
}

fn clean(opts: CleanOptions) -> Result<()> {
    let cwd = std::env::current_dir()
        .context("Failed to determine current directory")?;

    println!("Parcel Clean — rolling back build artifacts\n");
    println!("  working directory: {}", cwd.display());
    println!();

    let mut removed = 0usize;
    let mut skipped = 0usize;

    // ── 1. Build cache ─────────────────────────────────────────────────
    let build_dir = cwd.join(".parcel-build");
    if remove_dir(&build_dir, opts.dry_run, "Build cache")? {
        removed += 1;
    } else {
        skipped += 1;
    }

    // ── 2. Cargo.lock at workspace root (generated by build) ────────────
    let cargo_lock = cwd.join(".parcel-build").join("Cargo.lock");
    if cargo_lock.exists() {
        remove_file(&cargo_lock, opts.dry_run, "  Cargo.lock")?;
    }

    // ── 3. dist/ (optional) ─────────────────────────────────────────────
    if opts.include_dist || opts.include_config {
        let dist_dir = cwd.join("dist");
        if remove_dir(&dist_dir, opts.dry_run, "Distribution output")? {
            removed += 1;
        } else {
            skipped += 1;
        }
    } else {
        println!("  [skip] dist/ (use --dist to include)");
        skipped += 1;
    }

    // ── 4. parcel.json and parcel/ (optional, full reset) ───────────────
    if opts.include_config {
        let parcel_json = cwd.join("parcel.json");
        if remove_file(&parcel_json, opts.dry_run, "Configuration file")? {
            removed += 1;
        } else {
            skipped += 1;
        }

        let parcel_dir = cwd.join("parcel");
        if remove_dir(&parcel_dir, opts.dry_run, "Resource directory")? {
            removed += 1;
        } else {
            skipped += 1;
        }
    } else {
        println!("  [skip] parcel.json & parcel/ (use --all to include)");
        skipped += 1;
    }

    // ── Summary ─────────────────────────────────────────────────────────
    println!();
    if opts.dry_run {
        println!("  Dry-run complete. {} items would be removed, {} skipped.", removed, skipped);
    } else {
        println!("  Done. {} items removed, {} skipped.", removed, skipped);
    }

    Ok(())
}

/// Remove a directory if it exists.  Returns true if removed.
fn remove_dir(path: &Path, dry_run: bool, label: &str) -> Result<bool> {
    if !path.exists() {
        println!("  [skip] {} — not found: {}", label, path.display());
        return Ok(false);
    }

    // Safety: refuse to remove directories outside the CWD.
    let cwd = std::env::current_dir()
        .context("Failed to determine current directory")?;
    if let Ok(canonical) = path.canonicalize() {
        if !canonical.starts_with(cwd.canonicalize().unwrap_or(cwd.clone())) {
            println!("  [SAFE] Refusing to remove {} — outside working directory!", label);
            return Ok(false);
        }
    }

    if dry_run {
        println!("  [DRY]  Would remove: {} ({})", label, path.display());
        return Ok(true);
    }

    match std::fs::remove_dir_all(path) {
        Ok(_) => {
            println!("  [DEL]  Removed: {} ({})", label, path.display());
            Ok(true)
        }
        Err(e) => {
            println!("  [ERR]  Failed to remove {}: {e}", label);
            Ok(false)
        }
    }
}

/// Remove a file if it exists.  Returns true if removed.
fn remove_file(path: &Path, dry_run: bool, label: &str) -> Result<bool> {
    if !path.exists() {
        println!("  [skip] {} — not found: {}", label, path.display());
        return Ok(false);
    }

    if dry_run {
        println!("  [DRY]  Would remove: {} ({})", label, path.display());
        return Ok(true);
    }

    match std::fs::remove_file(path) {
        Ok(_) => {
            println!("  [DEL]  Removed: {} ({})", label, path.display());
            Ok(true)
        }
        Err(e) => {
            println!("  [ERR]  Failed to remove {}: {e}", label);
            Ok(false)
        }
    }
}
